# Site settings
title: Design
email: design@design.com
description:  A blog about design
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
baseurl: '/design'
twitter_username: jdw_dev
github_username:  rljusticio

# Build settings
markdown: kramdown
permalink: /:title
