# Site settings
title: Design
email: design@design.com
description:  A blog about design
baseurl: "/design" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: jdw_dev
github_username:  rljusticio
paginate: 3

# Build settings
markdown: kramdown
permalink: /:title

#Default settings
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      author: Justin Walters
      layout: "post"
      category: design
      comments: true
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: page
